---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deploy.yaml
- manifests/hpa.yaml
configMapGenerator:
- envs:
  - runner.env
  name: github-runner-config
images:
- name: gcr.io/PROJECT_ID/github-runner-arm:stable
  newName: gcr.io/gh-runners-e2e/runner
  newTag: stable
